### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by szapp** [onmax/issue-form-parser#18]
Hello @onmax!

in light of the [deprecation of Node 16 in GitHub actions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20) and the [removal of Node 16 in the coming months](https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/), would you consider updating this action to Node 20?

I tried to open a pull request but I am not familiar with the devcontainer / Dockerfile setup.

I am actively using this action and very happy with your work and would appreciate if it can remain active!

**Comment by onmax** [comment]
Updated, let me know if there is any issue. Thank you!

```
  - name: Parse issue
    id: parse
    uses: onmax/issue-form-parser@v1.5
```

**Comment by szapp** [comment]
@onmax I gave it a quick test run on my end and it works flawlessly. Thank you for the quick update!
